"""Order model + created_at, OrderItem model + quantity

Revision ID: 2ab7a808d889
Revises: 3efb7341a092
Create Date: 2026-02-09 12:00:13.909834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab7a808d889'
down_revision: Union[str, None] = '3efb7341a092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_at')
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###
