"""Added OrderItem Model, order_item_mods table and relationships

Revision ID: 3efb7341a092
Revises: ce45db23d2ce
Create Date: 2026-02-07 16:43:45.388686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efb7341a092'
down_revision: Union[str, None] = 'ce45db23d2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_order_items_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_mods',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], name=op.f('fk_order_item_mods_mod_id_mods')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_order_item_mods_order_item_id_order_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id', 'mod_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_mods')
    op.drop_table('order_items')
    # ### end Alembic commands ###
