"""changed order_item_mod table to association object with table

Revision ID: bfbdb9bb5b67
Revises: 2ab7a808d889
Create Date: 2026-02-12 23:03:48.462725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbdb9bb5b67'
down_revision: Union[str, None] = '2ab7a808d889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_mods',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], name=op.f('fk_order_item_mods_mod_id_mods')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_order_item_mods_order_item_id_order_items')),
    sa.PrimaryKeyConstraint('order_item_id', 'mod_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_mods')
    # ### end Alembic commands ###
