"""Added Mod model

Revision ID: d11f19e19cc8
Revises: 03c00899976d
Create Date: 2026-02-07 13:56:46.844771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11f19e19cc8'
down_revision: Union[str, None] = '03c00899976d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_item', sa.String(), nullable=False),
    sa.Column('mod_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mods')
    # ### end Alembic commands ###
